
--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Mar 08 2018 14:30
-- Script Generated by Database Design Studio 2.21.2 
--


--
-- Select Database: 'db_name'
--
USE db_name
GO

IF DB_NAME() = 'db_name'
    RAISERROR('''db_name'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
GO

EXECUTE SP_DBOPTION 'db_name' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Person TO public
GO

GRANT ALL ON By_Postnummer TO public
GO

GRANT ALL ON TelefonNummer TO public
GO

GRANT ALL ON Adresse TO public
GO

GRANT ALL ON PharA TO public
GO
